import type { Metadata } from "next";
import "./globals.css";
import { inter } from '@/app/ui/fonts';

export const metadata: Metadata = {
  title: "Michael Fryer Website",
  description: "Generated by Michael Fryer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* TODO metadata */}
      </head>
      <body className={`${inter.className} antialiased`}>
        <nav>
          {/* TODO make component */}
          Hey, I'm a nav!
        </nav>
        <article className="">
          {children}
        </article>
        <footer className="">
          {/* TODO make component */}
          <span>Hey, I'm a footer!</span>
        </footer>
      </body>
    </html>
  );
}
